// accommodations
export const ADD_ACCOMMODATION = 'ADD_ACCOMMODATION';
export const ADD_ACCOMMODATIONS = 'ADD_ACCOMMODATIONS';
export const RESET_ACCOMMODATIONS_META = 'RESET_ACCOMMODATIONS_META';

// auth
export const AUTH_ADMIN = 'AUTH_ADMIN';
export const UNAUTH_ADMIN = 'UNAUTH_ADMIN';
export const AUTH_ERROR = 'AUTH_ERROR';
export const COMMON_ERROR = 'COMMON_ERROR';

// adminMessages;
export const ADD_ADMIN_MESSAGE = 'ADD_ADMIN_MESSAGE';
export const ADD_ADMIN_MESSAGE_ERROR = 'ADD_ADMIN_MESSAGE_ERROR';
export const DELETE_ADMIN_MESSAGE = 'DELETE_ADMIN_MESSAGE';
export const ADD_ADMIN_MESSAGES = 'ADD_ADMIN_MESSAGES';
export const ADD_ADMIN_MESSAGES_ERROR = 'ADD_ADMIN_MESSAGES_ERROR';
export const DELETE_ADMIN_MESSAGES_SUCCESS_ERROR = 'DELETE_ADMIN_MESSAGES_SUCCESS_ERROR';

// admins
export const ADD_ADMIN = 'ADD_ADMIN';
export const ADD_ADMIN_ERROR = 'ADD_ADMIN_ERROR';
export const DELETE_ADMIN = 'DELETE_ADMIN';
export const ADD_ADMINS = 'ADD_ADMINS';
export const ADD_ADMINS_ERROR = 'ADD_ADMINS_ERROR';
export const DELETE_ADMINS_SUCCESS_ERROR = 'DELETE_ADMINS_SUCCESS_ERROR';

// bannedWords
export const POST_BANNED_WORD = 'POST_BANNED_WORD';
export const POST_BANNED_WORD_ERROR = 'POST_BANNED_WORD_ERROR';
export const ADD_BANNED_WORDS = 'ADD_BANNED_WORDS';
export const ADD_BANNED_WORDS_ERROR = 'ADD_BANNED_WORDS_ERROR';
export const ADD_BANNED_WORD = 'ADD_BANNED_WORD';
export const DELETE_BANNED_WORD_AT = 'DELETE_BANNED_WORD_AT';
export const ADD_BANNED_WORD_ERROR = 'ADD_BANNED_WORD_ERROR';
export const DELETE_BANNED_WORD = 'DELETE_BANNED_WORD';
export const DELETE_BANNED_WORDS_SUCCESS_ERROR = 'DELETE_BANNED_WORDS_SUCCESS_ERROR';
export const UPDATE_BANNED_WORD_AT = 'UPDATE_BANNED_WORD_AT,';

// cashLogs
export const ADD_CASH_LOGS = 'ADD_CASH_LOGS';
export const ADD_CASH_LOGS_ERROR = 'ADD_CASH_LOGS_ERROR';
export const UPDATE_CASH_LOGS_META = 'UPDATE_CASH_LOGS_META';
export const ADD_CASH_LOG = 'ADD_CASH_LOG';
export const ADD_CASH_LOG_ERROR = 'ADD_CASH_LOG_ERROR';
export const DELETE_CASH_LOG = 'DELETE_CASH_LOG';
export const DELETE_CASH_LOGS_SUCCESS_ERROR = 'DELETE_CASH_LOGS_SUCCESS_ERROR';

// cachoutRequests
export const ADD_CASHOUT_REQUESTS = 'ADD_CASHOUT_REQUESTS';
export const ADD_CASHOUT_REQUESTS_ERROR = 'ADD_CASHOUT_REQUESTS_ERROR';
export const UPDATE_CASHOUT_REQUESTS_META = 'UPDATE_CASHOUT_REQUESTS_META';
export const ADD_CASHOUT_REQUEST = 'ADD_CASHOUT_REQUEST';
export const ADD_CASHOUT_REQUEST_ERROR = 'ADD_CASHOUT_REQUEST_ERROR';
export const DELETE_CASHOUT_REQUEST = 'DELETE_CASHOUT_REQUEST';
export const DELETE_CASHOUT_REQUESTS_SUCCESS_ERROR = 'DELETE_CASHOUT_REQUESTS_SUCCESS_ERROR';

// groupChats
export const ADD_GROUP_CHATS = 'ADD_GROUP_CHATS';
export const ADD_GROUP_CHATROOMS = 'ADD_GROUP_CHATROOMS';
export const UPDATE_ITEM_IN_GROUP_CHATS = 'UPDATE_ITEM_IN_GROUP_CHATS';
export const UPDATE_ITEM_IN_GROUP_CHATROOMS = 'UPDATE_ITEM_IN_GROUP_CHATROOMS';
export const RESET_GROUP_CHATS = 'RESET_GROUP_CHATS';
export const UPDATE_GROUP_CHATS_META = 'UPDATE_GROUP_CHATS_META';

// meta
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const START_UPLOADING = 'START_UPLOADING';
export const STOP_UPLOADING = 'STOP_UPLOADING';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';

// modal
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';
export const SAVE_MODAL = 'SAVE_MODAL';
export const UPDATE_MODAL = 'UPDATE_MODAL';

// photos
export const ADD_PHOTOS = 'ADD_PHOTOS';
export const ADD_PHOTOS_ERROR = 'ADD_PHOTOS_ERROR';
export const ADD_PHOTO = 'ADD_PHOTO';
export const ADD_PHOTO_ERROR = 'ADD_PHOTO_ERROR';
export const DELETE_PHOTO = 'DELETE_PHOTO';
export const UPDATE_PHOTOS_META = 'UPDATE_PHOTOS_META';
export const DELETE_PHOTOS_SUCCESS_ERROR = 'DELETE_PHOTOS_SUCCESS_ERROR';

// photoComments
export const ADD_PHOTO_COMMENTS = 'ADD_PHOTO_COMMENTS';
export const ADD_PHOTO_COMMENTS_ERROR = 'ADD_PHOTO_COMMENTS_ERROR';
export const ADD_PHOTO_COMMENT = 'ADD_PHOTO_COMMENT';
export const ADD_PHOTO_COMMENT_ERROR = 'ADD_PHOTO_COMMENT_ERROR';
export const UPDATE_PHOTOS_COMMENTS_META = 'UPDATE_PHOTOS_COMMENTS_META';
export const DELETE_PHOTO_COMMENT = 'DELETE_PHOTO_COMMENT';
export const DELETE_PHOTO_COMMENTS_SUCCESS_ERROR = 'DELETE_PHOTO_COMMENTS_SUCCESS_ERROR';

// pointLogs
export const ADD_POINT_LOGS = 'ADD_POINT_LOGS';
export const ADD_POINT_LOGS_ERROR = 'ADD_POINT_LOGS_ERROR';
export const ADD_POINT_LOG = 'ADD_POINT_LOG';
export const ADD_POINT_LOG_ERROR = 'ADD_POINT_LOG_ERROR';
export const UPDATE_POINT_LOGS_META = 'UPDATE_POINT_LOGS_META';
export const DELETE_POINT_LOG = 'DELETE_POINT_LOG';
export const DELETE_POINT_LOGS_SUCCESS_ERROR = 'DELETE_POINT_LOGS_SUCCESS_ERROR';

// properties
export const ADD_PROPERTY = 'ADD_PROPERTY';
export const ADD_PROPERTIES = 'ADD_PROPERTIES';
export const UPDATE_ITEM_IN_PROPERTIES = 'UPDATE_ITEM_IN_PROPERTIES';
export const UPDATE_PROPERTIES_META = 'UPDATE_PROPERTIES_META';
export const RESET_PROPERTIES_META = 'RESET_PROPERTIES_META';

// purchaseLogs
export const ADD_PURCHASE_LOGS = 'ADD_PURCHASE_LOGS';
export const ADD_PURCHASE_LOGS_ERROR = 'ADD_PURCHASE_LOGS_ERROR';
export const UPDATE_PURCHASE_LOGS_META = 'UPDATE_PURCHASE_LOGS_META';
export const RESET_PURCHASE_LOGS_META = 'RESET_PURCHASE_LOGS_META';
export const ADD_PURCHASE_LOG = 'ADD_PURCHASE_LOG';
export const ADD_PURCHASE_LOG_ERROR = 'ADD_PURCHASE_LOG_ERROR';
export const DELETE_PURCHASE_LOG = 'DELETE_PURCHASE_LOG';
export const DELETE_PURCHASE_LOGS_SUCCESS_ERROR = 'DELETE_PURCHASE_LOGS_SUCCESS_ERROR';

// restaurants
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const ADD_RESTAURANTS = 'ADD_RESTAURANTS';
export const UPDATE_RESTAURANTS_META = 'UPDATE_RESTAURANTS_META';
export const RESET_RESTAURANTS_META = 'UPDATE_RESTAURANTS_META';

// stats
export const ADD_STATS = 'ADD_STATS';
export const UPDATE_STATS = 'UPDATE_STATS';

// story
//export const 

// talks
export const ADD_TALKS = 'ADD_TALKS';
export const ADD_TALKS_ERROR = 'ADD_TALKS_ERROR';
export const ADD_TALK = 'ADD_TALK';
export const ADD_TALK_ERROR = 'ADD_TALK_ERROR';
export const UPDATE_TALKS_META = 'UPDATE_TALKS_META';
export const DELETE_TALK = 'DELETE_TALK';
export const DELETE_TALKS_SUCCESS_ERROR = 'DELETE_TALKS_SUCCESS_ERROR';

// users
export const ADD_USER = 'ADD_USER';
export const ADD_USERS = 'ADD_USERS';
export const RESET_USERS_META = 'RESET_USERS_META';

// userUpdateLogs
export const ADD_USER_UPDATE_LOG = 'ADD_USER_UPDATE_LOG';
export const ADD_USER_UPDATE_LOG_ERROR = 'ADD_USER_UPDATE_LOG_ERROR';
export const ADD_USER_UPDATE_LOGS = 'ADD_USER_UPDATE_LOGS';
export const ADD_USER_UPDATE_LOGS_ERROR = 'ADD_USER_UPDATE_LOGS_ERROR';
export const DELETE_USER_UPDATE_LOG = 'DELETE_USER_UPDATE_LOG';
export const DELETE_USER_UPDATE_LOGS_SUCCESS_ERROR = 'DELETE_USER_UPDATE_LOGS_SUCCESS_ERROR';

// videoChatLogs
export const ADD_VIDEO_CHAT_LOGS = 'ADD_VIDEO_CHAT_LOGS';
export const ADD_VIDEO_CHAT_LOGS_ERROR = 'ADD_VIDEO_CHAT_LOGS_ERROR';
export const UPDATE_VIDEO_CHAT_LOGS_META = 'UPDATE_VIDEO_CHAT_LOGS_META';
export const ADD_VIDEO_CHAT_LOG = 'ADD_VIDEO_CHAT_LOG';
export const ADD_VIDEO_CHAT_LOG_ERROR = 'ADD_VIDEO_CHAT_LOG_ERROR';
export const DELETE_VIDEO_CHAT_LOG = 'DELETE_VIDEO_CHAT_LOG';
export const DELETE_VIDEO_CHAT_LOGS_SUCCESS_ERROR = 'DELETE_VIDEO_CHAT_LOGS_SUCCESS_ERROR';
